# Generated by Django 4.2.6 on 2023-10-29 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_incident_created_date_remove_incident_summary_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Reports",
            new_name="Report",
        ),
    ]
