# Generated by Django 4.2.6 on 2023-10-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_reports_report"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="report",
            name="incident",
        ),
        migrations.AddField(
            model_name="incident",
            name="reports",
            field=models.ManyToManyField(to="api.report"),
        ),
    ]
